# paths
paths:
  raw_data: "raw_data"
  figures: "figures"
  processed_data: "processed_data"
  cellpose_models: "../_pipeline_assets/cellpose_models"

# cellpose segmentation
segmentation:
  model_name: "cpsam_20x_downsampeled_20250630"
  use_gpu: true
  scale_factor: 0.1
  buffer_size: 10

# spotiflow detection
detection:
  footprint:
  - [1, 0, 1, 0, 1]
  - [0, 1, 1, 1, 0]
  - [1, 1, 1, 1, 1]
  - [0, 1, 1, 1, 0]
  - [1, 0, 1, 0, 1]
  min_distance: 10
