# experiment metadata
experiment:
  thickness_um: 20

# paths
paths:
  raw_data: "raw_data"
  figures: "figures"
  processed_data: "processed_data"
  cellpose_models: "../_pipeline_assets/cellpose_models"

# channels
channels:
  brightfield: 0
  spots: 1
  bags: 2

# cellpose segmentation
segmentation:
  model_name: "cpsam_20x_downsampeled_20250630"
  use_gpu: true
  scale_factor: 0.1
  buffer_size: 10

# spotiflow detection
detection:
  footprint:
  - [1, 0, 1, 0, 1]
  - [0, 1, 1, 1, 0]
  - [1, 1, 1, 1, 1]
  - [0, 1, 1, 1, 0]
  - [1, 0, 1, 0, 1]
  min_distance: 10

# analysis parameters
analysis:
  min_roi_area_um2: 3000

# QC figure settings
qc:
  save_figure: true
  dpi: 300
  figsize: [10, 8]